import os
import unittest
from src.custom_json import obj2pretty_json
from src.lib import report_to_obj


class TestReportToObj(unittest.TestCase):
    def test_01_a(self):
        file_path = os.path.join("files", "01_a_ksiazka.pdf")
        obj = report_to_obj(file_path)
        # print(obj2pretty_json(obj))

        self.assertEqual(obj["term"], "X")
        self.assertEqual(obj["sitting_number"], "1")
        self.assertEqual(obj["session_date"].isoformat(), "2023-11-13T00:00:00")
        self.assertEqual(obj["session_start"].isoformat(), "12:07:00")
        self.assertEqual(
            obj["table_of_contents"],
            [
                {
                    "type": "HEADER",
                    "name": "Otwarcie 1. posiedzenia Sejmu RP X kadencji",
                    "speakers": [
                        {"position": "Marszałek Senior", "name": "Marek Sawicki"}
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Przemówienie Prezydenta RP",
                    "speakers": [{"position": "Prezydent RP", "name": "Andrzeja Dudy"}],
                },
                {
                    "type": "HEADER",
                    "name": "Przemówienie Marszałka Seniora",
                    "speakers": [
                        {"position": "Marszałek Senior", "name": "Marka Sawickiego"}
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Powołanie tymczasowych sekretarzy Sejmu Ślubowanie poselskie",
                    "speakers": [
                        {"position": "Sekretarz Poseł", "name": "Bożena Żelazowska"},
                        {
                            "position": "Sekretarz Poseł",
                            "name": "Alicja Łepkowska-Gołaś",
                        },
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Wystąpienie prezesa Rady Ministrów",
                    "speakers": [
                        {
                            "position": "Prezes Rady Ministrów",
                            "name": "Mateusza Morawieckiego",
                        }
                    ],
                },
                {"type": "BREAK"},
                {"type": "RESUME OBRADY"},
                {
                    "type": "HEADER",
                    "name": "Punkt 1. porządku dziennego: Wybór marszałka Sejmu Rzeczypospolitej Polskiej",
                    "speakers": [
                        {"position": "Poseł", "name": "Władysław Kosiniak-Kamysz"},
                        {"position": "Poseł", "name": "Mariusz Błaszczak"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [
                        {"position": "Marszałek Senior", "name": "Marek Sawicki"},
                        {"position": "Marszałek", "name": "Marszałek"},
                    ],
                },
                {"type": "BREAK"},
                {"type": "RESUME OBRADY"},
                {
                    "type": "HEADER",
                    "name": "Punkt 2. porządku dziennego: Poselskie projekty uchwał w sprawie ustalenia liczby wicemarszałków Sejmu Rzeczypospolitej Polskiej",
                    "speakers": [
                        {"position": "Poseł", "name": "Stanisław Tyszka"},
                        {"position": "Poseł", "name": "Borys Budka"},
                        {"position": "Poseł", "name": "Krzysztof Paszyk"},
                        {"position": "Poseł", "name": "Paulina Hennig-Kloska"},
                        {"position": "Poseł", "name": "Krzysztof Gawkowski"},
                        {"position": "Poseł", "name": "Łukasz Schreiber"},
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {"type": "BREAK"},
                {"type": "RESUME OBRADY"},
                {
                    "type": "HEADER",
                    "name": "Punkt 3. porządku dziennego: Wybór wicemarszałków Sejmu Rzeczypospolitej Polskiej",
                    "speakers": [
                        {"position": "Poseł", "name": "Michał Wawer"},
                        {"position": "Poseł", "name": "Krzysztof Gawkowski"},
                        {"position": "Poseł", "name": "Borys Budka"},
                        {"position": "Poseł", "name": "Jarosław Kaczyński"},
                        {"position": "Poseł", "name": "Władysław Kosiniak-Kamysz"},
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {"type": "BREAK"},
            ],
        )

    def test_01_b(self):
        file_path = os.path.join("files", "01_b_ksiazka.pdf")
        obj = report_to_obj(file_path)
        # print(obj2pretty_json(obj))

        self.assertEqual(obj["term"], "X")
        self.assertEqual(obj["sitting_number"], "1")
        self.assertEqual(obj["session_date"].isoformat(), "2023-11-14T00:00:00")
        self.assertEqual(obj["session_start"].isoformat(), "16:33:00")
        self.assertEqual(
            obj["table_of_contents"],
            [
                {"type": "RESUME POSIEDZENIE"},
                {
                    "type": "HEADER",
                    "name": "Zmiana porządku dziennego",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 4. porządku dziennego: Wybór sekretarzy Sejmu",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 5. porządku dziennego: Wybór składu osobowego Komisji Regulaminowej, Spraw Poselskich i Immunitetowych",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 6. porządku dziennego: Pierwsze czytanie przedstawionego przez Prezydium Sejmu projektu uchwały w sprawie ustalenia liczby członków Komisji do Spraw Służb Specjalnych",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 7. porządku dziennego: Wybór posłów-członków Krajowej Rady Sądownictwa",
                    "speakers": [
                        {"position": "Poseł", "name": "Anna Milczanowska"},
                        {"position": "Poseł", "name": "Borys Budka"},
                        {
                            "position": "Minister Sprawiedliwości",
                            "name": "Zbigniew Ziobro",
                        },
                        {"position": "Poseł", "name": "Krzysztof Śmiszek"},
                        {
                            "position": "Minister Edukacji i Nauki",
                            "name": "Przemysław Czarnek",
                        },
                        {"position": "Poseł", "name": "Mirosław Suchoń"},
                        {
                            "position": "Minister – Członek Rady Ministrów",
                            "name": "Łukasz Schreiber",
                        },
                        {
                            "position": "Minister do Spraw Unii Europejskiej",
                            "name": "Szymon Szynkowski vel Sęk",
                        },
                        {"position": "Poseł", "name": "Krzysztof Szczucki"},
                        {"position": "Poseł", "name": "Sebastian Kaleta"},
                        {"position": "Poseł", "name": "Arkadiusz Myrcha"},
                        {"position": "Poseł", "name": "Michał Gramatyka"},
                        {"position": "Poseł", "name": "Krzysztof Paszyk"},
                        {"position": "Poseł", "name": "Krzysztof Gawkowski"},
                        {
                            "position": "Minister Edukacji i Nauki",
                            "name": "Przemysław Czarnek",
                        },
                        {"position": "Poseł", "name": "Michał Wawer"},
                        {
                            "position": "Minister – Członek Rady Ministrów",
                            "name": "Michał Wójcik",
                        },
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {"type": "BREAK"},
            ],
        )

    def test_01_c(self):
        file_path = os.path.join("files", "01_c_ksiazka_bis.pdf")
        obj = report_to_obj(file_path)
        # print(obj2pretty_json(obj))

        self.assertEqual(obj["term"], "X")
        self.assertEqual(obj["sitting_number"], "1")
        self.assertEqual(obj["session_date"].isoformat(), "2023-11-21T00:00:00")
        self.assertEqual(obj["session_start"].isoformat(), "12:04:00")
        self.assertEqual(
            obj["table_of_contents"],
            [
                {"type": "RESUME POSIEDZENIE"},
                {
                    "type": "HEADER",
                    "name": "Zmiana porządku dziennego",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [
                        {"position": "Poseł", "name": "Stefan Krajewski"},
                        {"position": "Poseł", "name": "Andrzej Adamczyk"},
                    ],
                },
                {"type": "BREAK"},
                {"type": "RESUME OBRADY"},
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [
                        {"position": "Poseł", "name": "Michał Wawer"},
                        {"position": "Poseł", "name": "Paweł Jabłoński"},
                        {"position": "Poseł", "name": "Konrad Berkowicz"},
                        {"position": "Poseł", "name": "Maciej Konieczny"},
                        {
                            "position": "Minister do Spraw Unii Europejskiej",
                            "name": "Szymon Szynkowski vel Sęk",
                        },
                        {"position": "Poseł", "name": "Paweł Zalewski"},
                        {
                            "position": "Sekretarz Stanu w Ministerstwie Spraw Zagranicznych",
                            "name": "Paweł Jabłoński",
                        },
                        {
                            "position": "Minister – Członek Rady Ministrów",
                            "name": "Michał Wójcik",
                        },
                        {
                            "position": "Minister – Członek Rady Ministrów",
                            "name": "Łukasz Schreiber",
                        },
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 8. porządku dziennego: Wybór składów osobowych komisji sejmowych",
                    "speakers": [
                        {
                            "position": "Sekretarz Stanu w Ministerstwie Spraw Zagranicznych",
                            "name": "Paweł Jabłoński",
                        }
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 9. porządku dziennego: Wybór składu osobowego Komisji do Spraw Unii Europejskiej",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 10. porządku dziennego: Wybór składu osobowego Komisji Etyki Poselskiej",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 11. porządku dziennego: Wybór składu osobowego Komisji do Spraw Służb Specjalnych",
                    "speakers": [
                        {"position": "Poseł", "name": "Marek Suski"},
                        {"position": "Poseł", "name": "Zbigniew Konwiński"},
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 12. porządku dziennego: Wybór członków Trybunału Stanu",
                    "speakers": [
                        {"position": "Poseł", "name": "Lidia Burzyńska"},
                        {"position": "Poseł", "name": "Arkadiusz Myrcha"},
                        {"position": "Poseł", "name": "Krzysztof Śmiszek"},
                        {"position": "Poseł", "name": "Robert Kropiwnicki"},
                        {"position": "Poseł", "name": "Sławomir Nitras"},
                        {"position": "Poseł", "name": "Krzysztof Paszyk"},
                        {"position": "Poseł", "name": "Piotr Zgorzelski"},
                        {"position": "Poseł", "name": "Paweł Śliz"},
                        {"position": "Poseł", "name": "Bartłomiej Pejo"},
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [
                        {"position": "Poseł", "name": "Paweł Jabłoński"},
                        {"position": "Poseł", "name": "Marek Sawicki"},
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Komunikaty",
                    "speakers": [
                        {
                            "position": "Sekretarz Poseł",
                            "name": "Aleksandra Karolina Wiśniewska",
                        }
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Oświadczenia",
                    "speakers": [
                        {"position": "Poseł", "name": "Antoni Macierewicz"},
                        {"position": "Poseł", "name": "Klaudia Jachira"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Tadeusz Tomaszewski"},
                        {"position": "Poseł", "name": "Grzegorz Lorek"},
                        {"position": "Poseł", "name": "Anna Wojciechowska"},
                    ],
                },
                {"type": "BREAK"},
            ],
        )

    def test_01_d(self):
        file_path = os.path.join("files", "01_d_ksiazka.pdf")
        obj = report_to_obj(file_path)
        # print(obj2pretty_json(obj))

        self.assertEqual(obj["term"], "X")
        self.assertEqual(obj["sitting_number"], "1")
        self.assertEqual(obj["session_date"].isoformat(), "2023-11-22T00:00:00")
        self.assertEqual(obj["session_start"].isoformat(), "11:06:00")
        self.assertEqual(
            obj["table_of_contents"],
            [
                {"type": "RESUME POSIEDZENIE"},
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [
                        {"position": "Poseł", "name": "Grzegorz Adam Płaczek"},
                        {"position": "Poseł", "name": "Waldemar Buda"},
                        {"position": "Poseł", "name": "Paulina Hennig-Kloska"},
                        {"position": "Poseł", "name": "Adrian Zandberg"},
                        {
                            "position": "Minister do spraw Unii Europejskiej",
                            "name": "Szymon Szynkowski vel Sęk",
                        },
                    ],
                },
                {"type": "BREAK"},
                {"type": "RESUME OBRADY"},
                {
                    "type": "HEADER",
                    "name": "Punkt 13. porządku dziennego: Pierwsze czytanie obywatelskiego projektu ustawy o zmianie ustawy o świadczeniach opieki zdrowotnej finansowanych ze środków publicznych",
                    "speakers": [
                        {
                            "position": "Przedstawiciel Komitetu Inicjatywy Ustawodawczej",
                            "name": "Agnieszka Pomaska",
                        },
                        {"position": "Poseł", "name": "Józefa Szczurek-Żelazko"},
                        {"position": "Poseł", "name": "Monika Wielichowska"},
                        {"position": "Poseł", "name": "Barbara Nowacka"},
                        {"position": "Poseł", "name": "Wioleta Tomczak"},
                        {"position": "Poseł", "name": "Władysław Kosiniak-Kamysz"},
                        {"position": "Poseł", "name": "Agnieszka Maria Kłopotek"},
                        {"position": "Poseł", "name": "Wanda Nowicka"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Konrad Berkowicz"},
                        {"position": "Minister Zdrowia", "name": "Katarzyna Sójka"},
                        {"position": "Poseł", "name": "Anna Dąbrowska-Banaszek"},
                        {"position": "Poseł", "name": "Monika Rosa"},
                        {"position": "Poseł", "name": "Barbara Oliwiecka"},
                        {"position": "Poseł", "name": "Dariusz Klimczak"},
                        {"position": "Poseł", "name": "Joanna Scheuring-Wielgus"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Czesław Hoc"},
                        {"position": "Poseł", "name": "Bartosz Arłukowicz"},
                        {"position": "Poseł", "name": "Marcin Skonieczka"},
                        {"position": "Poseł", "name": "Krzysztof Paszyk"},
                        {"position": "Poseł", "name": "Marcelina Zawisza"},
                        {"position": "Poseł", "name": "Bolesław Piecha"},
                        {"position": "Poseł", "name": "Aleksandra Gajewska"},
                        {"position": "Poseł", "name": "Michał Gramatyka"},
                        {"position": "Poseł", "name": "Jarosław Rzepa"},
                        {"position": "Poseł", "name": "Paulina Matysiak"},
                        {"position": "Poseł", "name": "Sławomir Nitras"},
                        {"position": "Poseł", "name": "Urszula Pasławska"},
                        {"position": "Poseł", "name": "Daria Gosek-Popiołek"},
                        {"position": "Poseł", "name": "Piotr Uściński"},
                        {"position": "Poseł", "name": "Marta Wcisło"},
                        {"position": "Poseł", "name": "Joanna Wicha"},
                        {"position": "Poseł", "name": "Katarzyna Maria Piekarska"},
                        {"position": "Poseł", "name": "Dorota Olko"},
                        {"position": "Poseł", "name": "Paweł Szrot"},
                        {"position": "Poseł", "name": "Katarzyna Anna Lubnauer"},
                        {"position": "Poseł", "name": "Adrian Zandberg"},
                        {"position": "Poseł", "name": "Andrzej Gawron"},
                        {"position": "Poseł", "name": "Marzena Okła-Drewnowicz"},
                        {"position": "Poseł", "name": "Tomasz Dominik Trela"},
                        {"position": "Poseł", "name": "Maria Kurowska"},
                        {"position": "Poseł", "name": "Cezary Tomczyk"},
                        {"position": "Poseł", "name": "Wanda Nowicka"},
                        {"position": "Poseł", "name": "Dariusz Matecki"},
                        {"position": "Poseł", "name": "Klaudia Jachira"},
                        {"position": "Poseł", "name": "Anita Kucharska-Dziedzic"},
                        {"position": "Poseł", "name": "Michał Szczerba"},
                        {"position": "Poseł", "name": "Anna Wojciechowska"},
                        {"position": "Poseł", "name": "Arkadiusz Marchewka"},
                        {"position": "Poseł", "name": "Krystyna Skowrońska"},
                        {"position": "Poseł", "name": "Jarosław Wałęsa"},
                        {"position": "Poseł", "name": "Zofia Czernow"},
                        {"position": "Poseł", "name": "Dariusz Joński"},
                        {"position": "Poseł", "name": "Małgorzata Tracz"},
                        {"position": "Poseł", "name": "Urszula Sara Zielińska"},
                        {"position": "Poseł", "name": "Krzysztof Habura"},
                        {"position": "Poseł", "name": "Karolina Pawliczak"},
                        {"position": "Poseł", "name": "Piotr Borys"},
                        {"position": "Poseł", "name": "Katarzyna Matusik-Lipiec"},
                        {"position": "Poseł", "name": "Adam Szłapka"},
                        {"position": "Poseł", "name": "Jakub Rutnicki"},
                        {"position": "Poseł", "name": "Katarzyna Kierzek-Koperska"},
                        {"position": "Poseł", "name": "Przemysław Witek"},
                        {"position": "Poseł", "name": "Witold Zembaczyński"},
                        {"position": "Poseł", "name": "Paweł Bliźniuk"},
                        {"position": "Poseł", "name": "Maria Małgorzata Janyska"},
                        {"position": "Poseł", "name": "Krystyna Sibińska"},
                        {"position": "Poseł", "name": "Elżbieta Gapińska"},
                        {"position": "Poseł", "name": "Iwona Maria Kozłowska"},
                        {"position": "Poseł", "name": "Grzegorz Rusiecki"},
                        {"position": "Poseł", "name": "Mateusz Bochenek"},
                        {"position": "Poseł", "name": "Marcin Józefaciuk"},
                        {"position": "Poseł", "name": "Marek Rząsa"},
                        {"position": "Poseł", "name": "Jolanta Niezgodzka"},
                        {"position": "Poseł", "name": "Krzysztof Truskolaski"},
                        {"position": "Poseł", "name": "Małgorzata Niemczyk"},
                        {"position": "Poseł", "name": "Konrad Frysztak"},
                        {"position": "Poseł", "name": "Maciej Wróbel"},
                        {"position": "Poseł", "name": "Patryk Jaskulski"},
                        {"position": "Poseł", "name": "Michał Krawczyk"},
                        {"position": "Poseł", "name": "Iwona Hartwich"},
                        {"position": "Poseł", "name": "Artur Daniel Gierada"},
                        {"position": "Poseł", "name": "Aleksander Miszalski"},
                        {"position": "Poseł", "name": "Franciszek Sterczewski"},
                        {"position": "Poseł", "name": "Krystyna Szumilas"},
                        {"position": "Poseł", "name": "Agnieszka Hanajczyk"},
                        {"position": "Poseł", "name": "Artur Jarosław Łącki"},
                        {"position": "Poseł", "name": "Adrian Witczak"},
                        {"position": "Poseł", "name": "Jan Krzysztof Ardanowski"},
                        {"position": "Poseł", "name": "Andrzej Szewiński"},
                        {"position": "Poseł", "name": "Łukasz Ściebiorowski"},
                        {"position": "Poseł", "name": "Krystian Łuczak"},
                        {"position": "Poseł", "name": "Mirosław Suchoń"},
                        {"position": "Poseł", "name": "Krzysztof Ciecióra"},
                        {"position": "Poseł", "name": "Piotr Kaleta"},
                        {
                            "position": "Zastępca Przedstawiciela Komitetu Inicjatywy Ustawodawczej",
                            "name": "Małgorzata Rozenek-Majdan",
                        },
                        {
                            "position": "Przedstawiciel Komitetu Inicjatywy Ustawodawczej",
                            "name": "Agnieszka Pomaska",
                        },
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Oświadczenia",
                    "speakers": [
                        {"position": "Poseł", "name": "Grzegorz Lorek"},
                        {"position": "Poseł", "name": "Mariusz Krystian"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Iwona Małgorzata Krawczyk"},
                        {"position": "Poseł", "name": "Paulina Matysiak"},
                        {"position": "Poseł", "name": "Katarzyna Maria Piekarska"},
                        {"position": "Poseł", "name": "Klaudia Jachira"},
                        {"position": "Poseł", "name": "Łukasz Horbatowski"},
                        {"position": "Poseł", "name": "Marek Jan Chmielewski"},
                        {"position": "Poseł", "name": "Norbert Jakub Kaczmarczyk"},
                        {"position": "Poseł", "name": "Jarosław Wałęsa"},
                    ],
                },
                {"type": "BREAK"},
            ],
        )

    def test_01_e(self):
        file_path = os.path.join("files", "01_e_ksiazka_bis.pdf")
        obj = report_to_obj(file_path)
        # print(obj2pretty_json(obj))

        self.assertEqual(obj["term"], "X")
        self.assertEqual(obj["sitting_number"], "1")
        self.assertEqual(obj["session_date"].isoformat(), "2023-11-28T00:00:00")
        self.assertEqual(obj["session_start"].isoformat(), "12:05:00")
        self.assertEqual(
            obj["table_of_contents"],
            [
                {"type": "RESUME POSIEDZENIE"},
                {
                    "type": "HEADER",
                    "name": "Zmiana porządku dziennego",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Komunikaty",
                    "speakers": [
                        {"position": "Sekretarz Poseł", "name": "Patryk Jaskulski"}
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [
                        {
                            "position": "Prezes Rady Ministrów",
                            "name": "Mateusz Morawiecki",
                        },
                        {"position": "Poseł", "name": "Waldemar Buda"},
                        {"position": "Poseł", "name": "Michał Wawer"},
                        {"position": "Poseł", "name": "Krzysztof Gawkowski"},
                    ],
                },
                {"type": "BREAK"},
                {"type": "RESUME OBRADY"},
                {
                    "type": "HEADER",
                    "name": "Punkt 14. porządku dziennego: Powołanie Rzecznika Praw Dziecka",
                    "speakers": [],
                },
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [{"position": "Poseł", "name": "Paweł Jabłoński"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 14. porządku dziennego (cd.)",
                    "speakers": [
                        {"position": "Poseł", "name": "Marzena Okła-Drewnowicz"},
                        {"position": "Poseł Sprawozdawca", "name": "Michał Krawczyk"},
                        {"position": "Poseł", "name": "Dorota Łoboda"},
                        {"position": "Poseł", "name": "Maja Ewa Nowak"},
                        {"position": "Poseł", "name": "Krzysztof Paszyk"},
                        {"position": "Poseł", "name": "Zbigniew Bogucki"},
                        {"position": "Poseł", "name": "Katarzyna Kotula"},
                        {"position": "Poseł", "name": "Grzegorz Adam Płaczek"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 15. porządku dziennego: Powołanie członka Państwowej Komisji do spraw przeciwdziałania wykorzystaniu seksualnemu małoletnich poniżej lat 15",
                    "speakers": [
                        {
                            "position": "Poseł Sprawozdawca",
                            "name": "Katarzyna Ueberhan",
                        },
                        {"position": "Poseł", "name": "Zbigniew Bogucki"},
                        {"position": "Poseł", "name": "Joanna Mucha"},
                        {"position": "Poseł", "name": "Katarzyna Ueberhan"},
                        {"position": "Poseł", "name": "Monika Rosa"},
                        {"position": "Poseł", "name": "Konrad Berkowicz"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 16. porządku dziennego: Pierwsze czytanie przedstawionego przez Prezydium Sejmu projektu uchwały w sprawie powołania i wyboru składu osobowego Komisji Nadzwyczajnej do spraw zmian w kodyfikacjach",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 13. porządku dziennego: Pierwsze czytanie obywatelskiego projektu ustawy o zmianie ustawy o świadczeniach opieki zdrowotnej finansowanych ze środków publicznych (cd.)",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {"type": "BREAK"},
                {"type": "RESUME OBRADY"},
                {
                    "type": "HEADER",
                    "name": "Punkt 17. porządku dziennego: Sprawozdanie Komisji Gospodarki i Rozwoju o poselskim projekcie ustawy o zmianie ustawy o ograniczeniu handlu w niedziele i święta oraz niektóre inne dni",
                    "speakers": [
                        {
                            "position": "Poseł Sprawozdawca",
                            "name": "Adam Michał Gomoła",
                        },
                        {"position": "Poseł", "name": "Urszula Rusecka"},
                        {"position": "Poseł", "name": "Michał Jaros"},
                        {"position": "Poseł", "name": "Maria Małgorzata Janyska"},
                        {"position": "Poseł", "name": "Izabela Bodnar"},
                        {"position": "Poseł", "name": "Magdalena Sroka"},
                        {"position": "Poseł", "name": "Izabela Bodnar"},
                        {"position": "Poseł", "name": "Maciej Konieczny"},
                        {"position": "Poseł", "name": "Przemysław Wipler"},
                        {"position": "Poseł", "name": "Grzegorz Lorek"},
                        {"position": "Poseł", "name": "Jarosław Wałęsa"},
                        {"position": "Poseł", "name": "Maciej Konieczny"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Klaudia Jachira"},
                        {"position": "Poseł", "name": "Adrian Zandberg"},
                        {"position": "Poseł", "name": "Marcin Porzucek"},
                        {"position": "Poseł", "name": "Małgorzata Pępek"},
                        {"position": "Poseł", "name": "Katarzyna Kierzek-Koperska"},
                        {"position": "Poseł", "name": "Paulina Matysiak"},
                        {"position": "Poseł", "name": "Mirosława Nykiel"},
                        {"position": "Poseł", "name": "Grzegorz Rusiecki"},
                        {"position": "Poseł", "name": "Konrad Frysztak"},
                        {"position": "Poseł", "name": "Krzysztof Truskolaski"},
                        {"position": "Poseł", "name": "Małgorzata Niemczyk"},
                        {"position": "Poseł", "name": "Łukasz Schreiber"},
                        {"position": "Poseł", "name": "Marta Wcisło"},
                        {"position": "Poseł", "name": "Mirosław Suchoń"},
                        {"position": "Poseł", "name": "Katarzyna Anna Lubnauer"},
                        {"position": "Poseł", "name": "Rafał Kasprzyk"},
                        {"position": "Poseł", "name": "Witold Zembaczyński"},
                        {"position": "Poseł", "name": "Michał Jaros"},
                        {"position": "Poseł", "name": "Jakub Rutnicki"},
                        {
                            "position": "Sekretarz Stanu w Ministerstwie Rodziny i Polityki Społecznej",
                            "name": "Stanisław Szwed",
                        },
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 18. porządku dziennego: Pierwsze czytanie poselskiego projektu uchwały w sprawie powołania Komisji Śledczej do zbadania legalności, prawidłowości oraz celowości działań podjętych w celu przygotowania i przeprowadzenia wyborów Prezydenta Rzeczypospolitej Polskiej w 2020 roku w formie głosowania korespondencyjnego",
                    "speakers": [
                        {"position": "Poseł", "name": "Zbigniew Konwiński"},
                        {"position": "Poseł", "name": "Przemysław Czarnek"},
                        {"position": "Poseł", "name": "Cezary Tomczyk"},
                        {"position": "Poseł", "name": "Michał Szczerba"},
                        {"position": "Poseł", "name": "Bartosz Romowicz"},
                        {"position": "Poseł", "name": "Marcin Skonieczka"},
                        {"position": "Poseł", "name": "Urszula Nowogórska"},
                        {"position": "Poseł", "name": "Joanna Scheuring-Wielgus"},
                        {"position": "Poseł", "name": "Witold Tumanowicz"},
                        {"position": "Poseł", "name": "Władysław Dajczak"},
                        {"position": "Poseł", "name": "Grzegorz Rusiecki"},
                        {"position": "Poseł", "name": "Michał Gramatyka"},
                        {"position": "Poseł", "name": "Bożena Żelazowska"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Mariusz Krystian"},
                        {"position": "Poseł", "name": "Mateusz Bochenek"},
                        {"position": "Poseł", "name": "Barbara Oliwiecka"},
                        {"position": "Poseł", "name": "Zbigniew Sosnowski"},
                        {"position": "Poseł", "name": "Mariusz Witczak"},
                        {"position": "Poseł", "name": "Mirosław Suchoń"},
                        {"position": "Poseł", "name": "Wanda Nowicka"},
                        {"position": "Poseł", "name": "Zbigniew Dolata"},
                        {"position": "Poseł", "name": "Małgorzata Tracz"},
                        {"position": "Poseł", "name": "Piotr Kaleta"},
                        {"position": "Poseł", "name": "Piotr Głowski"},
                        {"position": "Poseł", "name": "Robert Gontarz"},
                        {"position": "Poseł", "name": "Karolina Pawliczak"},
                        {"position": "Poseł", "name": "Łukasz Kmita"},
                        {"position": "Poseł", "name": "Elżbieta Anna Polak"},
                        {"position": "Poseł", "name": "Zbigniew Bogucki"},
                        {
                            "position": "Poseł",
                            "name": "Magdalena Małgorzata Kołodziejczak",
                        },
                        {"position": "Poseł", "name": "Łukasz Schreiber"},
                        {"position": "Poseł", "name": "Katarzyna Matusik-Lipiec"},
                        {"position": "Poseł", "name": "Małgorzata Niemczyk"},
                        {"position": "Poseł", "name": "Adrian Witczak"},
                        {"position": "Poseł", "name": "Sylwia Bielawska"},
                        {"position": "Poseł", "name": "Marek Jan Chmielewski"},
                        {"position": "Poseł", "name": "Łukasz Ściebiorowski"},
                        {"position": "Poseł", "name": "Zbigniew Konwiński"},
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 19. porządku dziennego: Pierwsze czytanie poselskiego projektu uchwały w sprawie powołania Komisji Śledczej do zbadania legalności, prawidłowości oraz celowości czynności operacyjno-rozpoznawczych podejmowanych m.in. z wykorzystaniem oprogramowania Pegasus przez członków Rady Ministrów, służby specjalne, Policję, organy kontroli skarbowej oraz celno-skarbowej w okresie od dnia 16 listopada 2015 r. do dnia 20 listopada 2023 r.",
                    "speakers": [
                        {"position": "Poseł", "name": "Robert Kropiwnicki"},
                        {"position": "Poseł", "name": "Michał Wójcik"},
                        {"position": "Poseł", "name": "Jacek Karnowski"},
                        {"position": "Poseł", "name": "Krzysztof Brejza"},
                        {"position": "Poseł", "name": "Paweł Śliz"},
                        {"position": "Poseł", "name": "Michał Gramatyka"},
                        {"position": "Poseł", "name": "Krzysztof Paszyk"},
                        {"position": "Poseł", "name": "Tomasz Trela"},
                        {"position": "Poseł", "name": "Sławomir Mentzen"},
                        {"position": "Poseł", "name": "Paweł Kukiz"},
                        {"position": "Poseł", "name": "Jacek Ozdoba"},
                        {"position": "Poseł", "name": "Marcin Bosacki"},
                        {"position": "Poseł", "name": "Izabela Bodnar"},
                        {"position": "Poseł", "name": "Wanda Nowicka"},
                        {"position": "Poseł", "name": "Przemysław Wipler"},
                        {"position": "Poseł", "name": "Dariusz Joński"},
                        {"position": "Poseł", "name": "Bartosz Romowicz"},
                        {"position": "Poseł", "name": "Magdalena Sroka"},
                        {"position": "Poseł", "name": "Roman Fritz"},
                        {"position": "Poseł", "name": "Piotr Adamowicz"},
                        {"position": "Poseł", "name": "Michał Gramatyka"},
                        {"position": "Poseł", "name": "Michał Pyrzyk"},
                        {"position": "Poseł", "name": "Krzysztof Truskolaski"},
                        {"position": "Poseł", "name": "Zbigniew Sosnowski"},
                        {"position": "Poseł", "name": "Witold Zembaczyński"},
                        {"position": "Poseł", "name": "Zofia Czernow"},
                        {"position": "Poseł", "name": "Krzysztof Habura"},
                        {"position": "Poseł", "name": "Klaudia Jachira"},
                        {"position": "Poseł", "name": "Mirosława Nykiel"},
                        {"position": "Poseł", "name": "Małgorzata Pępek"},
                        {"position": "Poseł", "name": "Jakub Rutnicki"},
                        {"position": "Poseł", "name": "Przemysław Witek"},
                        {"position": "Poseł", "name": "Łukasz Horbatowski"},
                        {"position": "Poseł", "name": "Anna Sobolak"},
                        {"position": "Poseł", "name": "Paweł Kukiz"},
                        {
                            "position": "Minister Sprawiedliwości",
                            "name": "Marcin Warchoł",
                        },
                        {"position": "Poseł", "name": "Krzysztof Brejza"},
                        {"position": "Poseł", "name": "Robert Kropiwnicki"},
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 20. porządku dziennego: Pierwsze czytanie poselskiego projektu uchwały w sprawie powołania Komisji Śledczej do zbadania legalności, prawidłowości oraz celowości działań, a także występowania nadużyć, zaniedbań i zaniechań w zakresie legalizacji pobytu cudzoziemców na terytorium Rzeczypospolitej Polskiej w okresie od dnia 1 stycznia 2019 r. do dnia 20 listopada 2023 r.",
                    "speakers": [
                        {"position": "Poseł", "name": "Tomasz Szymański"},
                        {"position": "Poseł", "name": "Paweł Jabłoński"},
                        {"position": "Poseł", "name": "Dariusz Joński"},
                        {"position": "Poseł", "name": "Sławomir Nitras"},
                        {"position": "Poseł", "name": "Ewa Schädler"},
                        {"position": "Poseł", "name": "Aleksandra Leo"},
                        {"position": "Poseł", "name": "Marek Biernacki"},
                        {"position": "Poseł", "name": "Maciej Konieczny"},
                        {"position": "Poseł", "name": "Krzysztof Mulawa"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Marek Jakubiak"},
                        {"position": "Poseł", "name": "Radosław Fogiel"},
                        {"position": "Poseł", "name": "Michał Szczerba"},
                        {"position": "Poseł", "name": "Agnieszka Buczyńska"},
                        {"position": "Poseł", "name": "Wanda Nowicka"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Konrad Frysztak"},
                        {"position": "Poseł", "name": "Rafał Kasprzyk"},
                        {"position": "Poseł", "name": "Jarosław Rzepa"},
                        {"position": "Poseł", "name": "Dariusz Wieczorek"},
                        {"position": "Poseł", "name": "Marek Krząkała"},
                        {"position": "Poseł", "name": "Adam Luboński"},
                        {"position": "Poseł", "name": "Piotr Borys"},
                        {"position": "Poseł", "name": "Urszula Sara Zielińska"},
                        {"position": "Poseł", "name": "Waldemar Sługocki"},
                        {"position": "Poseł", "name": "Marek Sowa"},
                        {"position": "Poseł", "name": "Marta Wcisło"},
                        {"position": "Poseł", "name": "Iwona Maria Kozłowska"},
                        {"position": "Poseł", "name": "Artur Jarosław Łącki"},
                        {"position": "Poseł", "name": "Jarosław Wałęsa"},
                        {"position": "Poseł", "name": "Anna Wojciechowska"},
                        {"position": "Poseł", "name": "Patryk Gabriel"},
                        {"position": "Poseł", "name": "Bartosz Zawieja"},
                        {"position": "Poseł", "name": "Dariusz Joński"},
                        {"position": "Poseł", "name": "Marcin Grabowski"},
                        {"position": "Poseł", "name": "Klaudia Jachira"},
                        {"position": "Poseł", "name": "Paweł Jabłoński"},
                        {"position": "Poseł", "name": "Tomasz Szymański"},
                        {"position": "Poseł", "name": "Radosław Fogiel"},
                        {"position": "Poseł", "name": "Michał Szczerba"},
                        {"position": "Poseł", "name": "Konrad Frysztak"},
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Oświadczenia",
                    "speakers": [
                        {"position": "Poseł", "name": "Klaudia Jachira"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Szymon Giżyński"},
                        {"position": "Poseł", "name": "Anna Dąbrowska-Banaszek"},
                        {"position": "Poseł", "name": "Michał Pyrzyk"},
                        {"position": "Poseł", "name": "Barbara Bartuś"},
                        {"position": "Poseł", "name": "Marcin Józefaciuk"},
                        {"position": "Poseł", "name": "Iwona Małgorzata Krawczyk"},
                        {"position": "Poseł", "name": "Andrzej Tomasz Zapałowski"},
                        {"position": "Poseł", "name": "Bartosz Romowicz"},
                        {"position": "Poseł", "name": "Maciej Wróbel"},
                        {"position": "Poseł", "name": "Tadeusz Samborski"},
                        {"position": "Poseł", "name": "Renata Urszula Rak"},
                        {"position": "Poseł", "name": "Sylwia Bielawska"},
                    ],
                },
                {"type": "BREAK"},
                {
                    "type": "HEADER",
                    "name": "Załącznik – Teksty wystąpień niewygłoszonych",
                    "speakers": [
                        {"position": "Poseł", "name": "Waldemar Andzel"},
                        {"position": "Poseł", "name": "Grzegorz Lorek"},
                        {"position": "Poseł", "name": "Tadeusz Tomaszewski"},
                    ],
                },
            ],
        )

    def test_01_f(self):
        file_path = os.path.join("files", "01_f_ksiazka.pdf")
        obj = report_to_obj(file_path)
        # print(obj2pretty_json(obj))

        self.assertEqual(obj["term"], "X")
        self.assertEqual(obj["sitting_number"], "1")
        self.assertEqual(obj["session_date"].isoformat(), "2023-11-29T00:00:00")
        self.assertEqual(obj["session_start"].isoformat(), "09:04:00")
        self.assertEqual(
            obj["table_of_contents"],
            [
                {"type": "RESUME POSIEDZENIE"},
                {
                    "type": "HEADER",
                    "name": "Komunikaty",
                    "speakers": [
                        {"position": "Sekretarz Poseł", "name": "Małgorzata Gromadzka"}
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Zmiana porządku dziennego",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [{"position": "Poseł", "name": "Włodzimierz Skalik"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 17. porządku dziennego: Sprawozdanie Komisji Gospodarki i Rozwoju o poselskim projekcie ustawy o zmianie ustawy o ograniczeniu handlu w niedziele i święta oraz niektóre inne dni",
                    "speakers": [
                        {
                            "position": "Poseł Sprawozdawca",
                            "name": "Adam Michał Gomoła",
                        },
                        {"position": "Poseł", "name": "Wojciech Michał Zubowski"},
                        {"position": "Poseł", "name": "Jakub Rutnicki"},
                        {"position": "Poseł", "name": "Adam Michał Gomoła"},
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 21. porządku dziennego: Pierwsze czytanie obywatelskiego projektu ustawy o zmianie ustawy o sposobie ustalania najniższego wynagrodzenia zasadniczego niektórych pracowników zatrudnionych w podmiotach leczniczych",
                    "speakers": [
                        {
                            "position": "Przedstawiciel Komitetu Inicjatywy Ustawodawczej",
                            "name": "Krystyna Ptok",
                        },
                        {"position": "Poseł", "name": "Katarzyna Sójka"},
                        {"position": "Poseł", "name": "Elżbieta Gelert"},
                        {"position": "Poseł", "name": "Ewa Szymanowska"},
                        {"position": "Poseł", "name": "Jarosław Rzepa"},
                        {"position": "Poseł", "name": "Joanna Wicha"},
                        {"position": "Poseł", "name": "Marcelina Zawisza"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Jarosław Sachajko"},
                        {"position": "Poseł", "name": "Czesław Hoc"},
                        {"position": "Poseł", "name": "Michał Szczerba"},
                        {"position": "Poseł", "name": "Wioleta Tomczak"},
                        {"position": "Poseł", "name": "Urszula Nowogórska"},
                        {"position": "Poseł", "name": "Maciej Konieczny"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Jarosław Sachajko"},
                        {"position": "Poseł", "name": "Józefa Szczurek-Żelazko"},
                        {"position": "Poseł", "name": "Małgorzata Pępek"},
                        {"position": "Poseł", "name": "Bożena Żelazowska"},
                        {"position": "Poseł", "name": "Daria Gosek-Popiołek"},
                        {"position": "Poseł", "name": "Ewa Leniart"},
                        {"position": "Poseł", "name": "Zofia Czernow"},
                        {"position": "Poseł", "name": "Marcin Skonieczka"},
                        {"position": "Poseł", "name": "Tadeusz Tomaszewski"},
                        {"position": "Poseł", "name": "Teresa Pamuła"},
                        {"position": "Poseł", "name": "Krystyna Skowrońska"},
                        {"position": "Poseł", "name": "Tomasz Zimoch"},
                        {"position": "Poseł", "name": "Dorota Olko"},
                        {"position": "Poseł", "name": "Marcin Porzucek"},
                        {"position": "Poseł", "name": "Marek Rząsa"},
                        {"position": "Poseł", "name": "Dariusz Joński"},
                        {"position": "Poseł", "name": "Wanda Nowicka"},
                        {"position": "Poseł", "name": "Anna Ewa Cicholska"},
                        {"position": "Poseł", "name": "Marek Tomasz Hok"},
                        {"position": "Poseł", "name": "Alicja Chybicka"},
                        {"position": "Poseł", "name": "Ewa Kołodziej"},
                        {"position": "Poseł", "name": "Konrad Frysztak"},
                        {"position": "Poseł", "name": "Marta Wcisło"},
                        {"position": "Poseł", "name": "Katarzyna Anna Lubnauer"},
                        {"position": "Poseł", "name": "Małgorzata Niemczyk"},
                        {"position": "Poseł", "name": "Grzegorz Rusiecki"},
                        {"position": "Poseł", "name": "Henryka Krzywonos-Strycharska"},
                        {"position": "Poseł", "name": "Agnieszka Hanajczyk"},
                        {"position": "Poseł", "name": "Barbara Dolniak"},
                        {"position": "Poseł", "name": "Michał Krawczyk"},
                        {"position": "Poseł", "name": "Witold Zembaczyński"},
                        {"position": "Poseł", "name": "Mateusz Bochenek"},
                        {
                            "position": "Podsekretarz Stanu w Ministerstwie Zdrowia",
                            "name": "Piotr Bromber",
                        },
                        {
                            "position": "Zastępca Przedstawiciela Komitetu Inicjatywy Ustawodawczej",
                            "name": "Iwona Borchulska",
                        },
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 22. porządku dziennego: Sprawozdanie Komisji Zdrowia o obywatelskim projekcie ustawy o zmianie ustawy o świadczeniach opieki zdrowotnej finansowanych ze środków publicznych",
                    "speakers": [],
                },
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [{"position": "Poseł", "name": "Grzegorz Braun"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 22. porządku dziennego (cd.)",
                    "speakers": [
                        {
                            "position": "Poseł Sprawozdawca",
                            "name": "Bartosz Arłukowicz",
                        },
                        {"position": "Poseł", "name": "Józefa Szczurek-Żelazko"},
                        {"position": "Poseł", "name": "Piotr Uściński"},
                        {"position": "Poseł", "name": "Monika Wielichowska"},
                        {"position": "Poseł", "name": "Agnieszka Pomaska"},
                        {"position": "Poseł", "name": "Barbara Nowacka"},
                        {"position": "Poseł", "name": "Wioleta Tomczak"},
                        {"position": "Poseł", "name": "Agnieszka Maria Kłopotek"},
                        {"position": "Poseł", "name": "Wanda Nowicka"},
                        {"position": "Poseł", "name": "Grzegorz Adam Płaczek"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Andrzej Gawron"},
                        {"position": "Poseł", "name": "Michał Szczerba"},
                        {"position": "Poseł", "name": "Sławomir Ćwik"},
                        {"position": "Poseł", "name": "Tadeusz Tomaszewski"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Anna Dąbrowska-Banaszek"},
                        {"position": "Poseł", "name": "Mateusz Bochenek"},
                        {"position": "Poseł", "name": "Marcelina Zawisza"},
                        {"position": "Poseł", "name": "Roman Fritz"},
                        {"position": "Poseł", "name": "Władysław Kurowski"},
                        {"position": "Poseł", "name": "Małgorzata Pępek"},
                        {"position": "Poseł", "name": "Kamil Wnuk"},
                        {"position": "Poseł", "name": "Wanda Nowicka"},
                        {"position": "Poseł", "name": "Piotr Paweł Strach"},
                        {"position": "Poseł", "name": "Paweł Szrot"},
                        {"position": "Poseł", "name": "Alicja Chybicka"},
                        {"position": "Poseł", "name": "Barbara Bartuś"},
                        {"position": "Poseł", "name": "Marcin Józefaciuk"},
                        {"position": "Poseł", "name": "Ewa Kołodziej"},
                        {"position": "Poseł", "name": "Krzysztof Ciecióra"},
                        {"position": "Poseł", "name": "Krzysztof Truskolaski"},
                        {"position": "Poseł", "name": "Piotr Kaleta"},
                        {"position": "Poseł", "name": "Konrad Frysztak"},
                        {"position": "Poseł", "name": "Marta Golbik"},
                        {"position": "Poseł", "name": "Kinga Gajewska"},
                        {"position": "Poseł", "name": "Małgorzata Niemczyk"},
                        {"position": "Poseł", "name": "Grzegorz Rusiecki"},
                        {"position": "Poseł", "name": "Monika Rosa"},
                        {"position": "Poseł", "name": "Iwona Małgorzata Krawczyk"},
                        {"position": "Poseł", "name": "Sylwia Bielawska"},
                        {"position": "Poseł", "name": "Anna Wojciechowska"},
                        {"position": "Poseł", "name": "Aleksandra Gajewska"},
                        {"position": "Poseł", "name": "Katarzyna Osos"},
                        {"position": "Poseł", "name": "Joanna Frydrych"},
                        {"position": "Poseł", "name": "Jakub Rutnicki"},
                        {"position": "Poseł", "name": "Witold Zembaczyński"},
                        {"position": "Poseł", "name": "Patryk Gabriel"},
                        {"position": "Poseł", "name": "Patryk Jaskulski"},
                        {"position": "Poseł", "name": "Iwona Maria Kozłowska"},
                        {"position": "Poseł", "name": "Lucjan Marek Pietrzczyk"},
                        {"position": "Poseł", "name": "Franciszek Sterczewski"},
                        {"position": "Poseł", "name": "Jarosław Wałęsa"},
                        {"position": "Poseł", "name": "Krzysztof Brejza"},
                        {"position": "Poseł", "name": "Michał Krawczyk"},
                        {"position": "Poseł", "name": "Jacek Niedźwiedzki"},
                        {"position": "Poseł", "name": "Jacek Karnowski"},
                        {"position": "Poseł", "name": "Paweł Bliźniuk"},
                        {"position": "Poseł", "name": "Jolanta Niezgodzka"},
                        {"position": "Poseł", "name": "Zbigniew Bogucki"},
                        {
                            "position": "Poseł",
                            "name": "Magdalena Małgorzata Kołodziejczak",
                        },
                        {"position": "Poseł", "name": "Piotr Borys"},
                        {"position": "Poseł", "name": "Łukasz Ściebiorowski"},
                        {"position": "Poseł", "name": "Mirosław Suchoń"},
                        {"position": "Poseł", "name": "Krystyna Skowrońska"},
                        {"position": "Poseł", "name": "Elżbieta Anna Polak"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {
                            "position": "Zastępca Przedstawiciela Komitetu Inicjatywy Ustawodawczej",
                            "name": "Małgorzata Rozenek-Majdan",
                        },
                        {
                            "position": "Przedstawiciel Komitetu Inicjatywy Ustawodawczej",
                            "name": "Agnieszka Pomaska",
                        },
                        {"position": "Poseł", "name": "Jacek Karnowski"},
                    ],
                },
                {"type": "BREAK"},
                {"type": "RESUME OBRADY"},
                {
                    "type": "HEADER",
                    "name": "Punkt 23. porządku dziennego: Informacja Prezesa Rady Ministrów w sprawie protestów polskich transportowców i rolników na granicy polsko-ukraińskiej",
                    "speakers": [
                        {
                            "position": "Minister Rolnictwa i Rozwoju Wsi",
                            "name": "Anna Gembicka",
                        },
                        {
                            "position": "Minister Infrastruktury",
                            "name": "Alvin Gajadhur",
                        },
                        {"position": "Poseł", "name": "Jakub Rutnicki"},
                        {"position": "Poseł", "name": "Piotr Król"},
                        {"position": "Poseł", "name": "Paweł Kowal"},
                        {"position": "Poseł", "name": "Michał Kołodziejczak"},
                        {"position": "Poseł", "name": "Marta Wcisło"},
                        {"position": "Poseł", "name": "Mirosław Suchoń"},
                        {"position": "Poseł", "name": "Dariusz Klimczak"},
                        {"position": "Poseł", "name": "Stefan Krajewski"},
                        {"position": "Poseł", "name": "Andrzej Adamczyk"},
                        {"position": "Poseł", "name": "Jacek Czerniak"},
                        {"position": "Poseł", "name": "Andrzej Tomasz Zapałowski"},
                        {"position": "Poseł", "name": "Witold Tumanowicz"},
                        {"position": "Poseł", "name": "Jarosław Sachajko"},
                        {"position": "Poseł", "name": "Stefan Krajewski"},
                        {"position": "Poseł", "name": "Zbigniew Krzysztof Kuźmiuk"},
                        {"position": "Poseł", "name": "Jarosław Wałęsa"},
                        {"position": "Poseł", "name": "Bartosz Romowicz"},
                        {"position": "Poseł", "name": "Andrzej Grzyb"},
                        {"position": "Poseł", "name": "Tadeusz Tomaszewski"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Jarosław Sachajko"},
                        {"position": "Poseł", "name": "Kazimierz Gwiazdowski"},
                        {"position": "Poseł", "name": "Stefan Krajewski"},
                        {"position": "Poseł", "name": "Artur Jarosław Łącki"},
                        {"position": "Poseł", "name": "Marcin Skonieczka"},
                        {"position": "Poseł", "name": "Wiesław Różyński"},
                        {"position": "Poseł", "name": "Paulina Matysiak"},
                        {"position": "Poseł", "name": "Krzysztof Ciecióra"},
                        {"position": "Poseł", "name": "Krystyna Skowrońska"},
                        {"position": "Poseł", "name": "Ewa Schädler"},
                        {"position": "Poseł", "name": "Krzysztof Paszyk"},
                        {"position": "Poseł", "name": "Jacek Czerniak"},
                        {"position": "Poseł", "name": "Dorota Marek"},
                        {"position": "Poseł", "name": "Barbara Oliwiecka"},
                        {"position": "Poseł", "name": "Henryk Kiepura"},
                        {"position": "Poseł", "name": "Krzysztof Truskolaski"},
                        {"position": "Poseł", "name": "Sławomir Ćwik"},
                        {"position": "Poseł", "name": "Mirosław Maliszewski"},
                        {"position": "Poseł", "name": "Michał Szczerba"},
                        {"position": "Poseł", "name": "Mirosław Suchoń"},
                        {"position": "Poseł", "name": "Adam Dziedzic"},
                        {"position": "Poseł", "name": "Agnieszka Maria Kłopotek"},
                        {"position": "Poseł", "name": "Grzegorz Rusiecki"},
                        {"position": "Poseł", "name": "Alicja Chybicka"},
                        {"position": "Poseł", "name": "Marek Rząsa"},
                        {"position": "Poseł", "name": "Kazimierz Plocke"},
                        {"position": "Poseł", "name": "Joanna Frydrych"},
                        {"position": "Poseł", "name": "Piotr Głowski"},
                        {"position": "Poseł", "name": "Marek Sowa"},
                        {"position": "Poseł", "name": "Małgorzata Pępek"},
                        {"position": "Poseł", "name": "Krystyna Sibińska"},
                        {"position": "Poseł", "name": "Zofia Czernow"},
                        {"position": "Poseł", "name": "Konrad Frysztak"},
                        {"position": "Poseł", "name": "Krzysztof Grabczuk"},
                        {"position": "Poseł", "name": "Marta Wcisło"},
                        {"position": "Poseł", "name": "Piotr Borys"},
                        {"position": "Poseł", "name": "Tomasz Piotr Nowak"},
                        {"position": "Poseł", "name": "Witold Zembaczyński"},
                        {"position": "Poseł", "name": "Danuta Jazłowiecka"},
                        {"position": "Poseł", "name": "Michał Kołodziejczak"},
                        {"position": "Poseł", "name": "Piotr Kandyba"},
                        {"position": "Poseł", "name": "Sebastian Kaleta"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Michał Szczerba"},
                        {
                            "position": "Minister Rolnictwa i Rozwoju Wsi",
                            "name": "Anna Gembicka",
                        },
                        {
                            "position": "Minister Infrastruktury",
                            "name": "Alvin Gajadhur",
                        },
                        {
                            "position": "Sekretarz Stanu w Ministerstwie Infrastruktury",
                            "name": "Rafał Weber",
                        },
                        {
                            "position": "Sekretarz Stanu w Ministerstwie Spraw Zagranicznych",
                            "name": "Paweł Jabłoński",
                        },
                    ],
                },
                {"type": "BREAK"},
                {"type": "RESUME OBRADY"},
                {
                    "type": "HEADER",
                    "name": "Zmiana porządku dziennego",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [{"position": "Poseł", "name": "Jacek Ozdoba"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 22. porządku dziennego: Sprawozdanie Komisji Zdrowia o obywatelskim projekcie ustawy o zmianie ustawy o świadczeniach opieki zdrowotnej finansowanych ze środków publicznych (cd.)",
                    "speakers": [
                        {"position": "Poseł Sprawozdawca", "name": "Bartosz Arłukowicz"}
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 23. porządku dziennego: Informacja Prezesa Rady Ministrów w sprawie protestów polskich transportowców i rolników na granicy polsko-ukraińskiej (cd.)",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 24. porządku dziennego: Odwołanie członków Państwowej Komisji do spraw badania wpływów rosyjskich na bezpieczeństwo wewnętrzne Rzeczypospolitej Polskiej w latach 2007–2022",
                    "speakers": [
                        {"position": "Poseł", "name": "Borys Budka"},
                        {
                            "position": "Prezes Rady Ministrów",
                            "name": "Mateusz Morawiecki",
                        },
                        {
                            "position": "Minister Obrony Narodowej",
                            "name": "Mariusz Błaszczak",
                        },
                        {"position": "Poseł", "name": "Borys Budka"},
                        {"position": "Poseł", "name": "Piotr Kaleta"},
                        {"position": "Poseł", "name": "Tomasz Szymański"},
                        {"position": "Poseł", "name": "Paweł Zalewski"},
                        {"position": "Poseł", "name": "Krzysztof Paszyk"},
                        {"position": "Poseł", "name": "Wiesław Szczepański"},
                        {"position": "Poseł", "name": "Przemysław Wipler"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Paweł Kukiz"},
                        {
                            "position": "Minister Spraw Wewnętrznych i Administracji",
                            "name": "Paweł Szefernaker",
                        },
                        {
                            "position": "Minister – Członek Rady Ministrów",
                            "name": "Jacek Ozdoba",
                        },
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 26. porządku dziennego: Wybór uzupełniający do składu osobowego Komisji do Spraw Unii Europejskiej",
                    "speakers": [
                        {"position": "Poseł", "name": "Marek Suski"},
                        {"position": "Poseł", "name": "Sławomir Nitras"},
                    ],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 25. porządku dziennego: Zmiany w składach osobowych komisji sejmowych",
                    "speakers": [],
                },
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [{"position": "Poseł", "name": "Zbigniew Konwiński"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 25. porządku dziennego (cd.)",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Oświadczenia",
                    "speakers": [
                        {"position": "Poseł", "name": "Klaudia Jachira"},
                        {"position": "Poseł", "name": "Szymon Giżyński"},
                        {"position": "Poseł", "name": "Anna Dąbrowska-Banaszek"},
                        {"position": "Poseł", "name": "Anna Wojciechowska"},
                        {"position": "Poseł", "name": "Jarosław Wałęsa"},
                        {"position": "Poseł", "name": "Adrian Witczak"},
                        {"position": "Poseł", "name": "Zofia Czernow"},
                        {"position": "Poseł", "name": "Bartosz Romowicz"},
                        {"position": "Poseł", "name": "Władysław Dajczak"},
                        {"position": "Poseł", "name": "Tadeusz Tomaszewski"},
                        {"position": "Poseł", "name": "Zbigniew Bogucki"},
                        {"position": "Poseł", "name": "Waldemar Andzel"},
                        {"position": "Poseł", "name": "Marcin Józefaciuk"},
                        {"position": "Poseł", "name": "Kamil Wnuk"},
                        {"position": "Poseł", "name": "Filip Kaczyński"},
                        {"position": "Poseł", "name": "Łukasz Ściebiorowski"},
                        {"position": "Poseł", "name": "Katarzyna Maria Piekarska"},
                        {"position": "Poseł", "name": "Łukasz Osmalak"},
                        {"position": "Poseł", "name": "Paweł Szrot"},
                        {"position": "Poseł", "name": "Tadeusz Samborski"},
                        {"position": "Poseł", "name": "Włodzimierz Skalik"},
                    ],
                },
                {"type": "BREAK"},
                {
                    "type": "HEADER",
                    "name": "Załącznik – Teksty wystąpień niewygłoszonych",
                    "speakers": [{"position": "Poseł", "name": "Grzegorz Lorek"}],
                },
            ],
        )

    def test_01_g(self):
        file_path = os.path.join("files", "01_g_ksiazka.pdf")
        obj = report_to_obj(file_path)
        # print(obj2pretty_json(obj))

        self.assertEqual(obj["term"], "X")
        self.assertEqual(obj["sitting_number"], "1")
        self.assertEqual(obj["session_date"].isoformat(), "2023-12-06T00:00:00")
        self.assertEqual(obj["session_start"].isoformat(), "09:03:00")
        self.assertEqual(
            obj["table_of_contents"],
            [
                {"type": "RESUME POSIEDZENIE"},
                {
                    "type": "HEADER",
                    "name": "Komunikaty",
                    "speakers": [
                        {"position": "Sekretarz Poseł", "name": "Jolanta Niezgodzka"}
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Zmiana porządku dziennego",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [
                        {"position": "Poseł", "name": "Ryszard Wilk"},
                        {"position": "Poseł", "name": "Zbigniew Krzysztof Kuźmiuk"},
                        {"position": "Poseł", "name": "Mirosław Suchoń"},
                        {"position": "Poseł", "name": "Jarosław Sachajko"},
                        {
                            "position": "Minister Rolnictwa i Rozwoju Wsi",
                            "name": "Anna Gembicka",
                        },
                        {"position": "Poseł", "name": "Stefan Krajewski"},
                        {
                            "position": "Minister Rolnictwa i Rozwoju Wsi",
                            "name": "Anna Gembicka",
                        },
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 27. porządku dziennego: Ślubowanie członka Państwowej Komisji do spraw przeciwdziałania wykorzystaniu seksualnemu małoletnich poniżej lat 15",
                    "speakers": [
                        {
                            "position": "Członek Państwowej Komisji do spraw Przeciwdziałania Wykorzystaniu Seksualnemu Małoletnich Poniżej Lat 15",
                            "name": "Karolina Maria Bućko",
                        }
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 28. porządku dziennego: Pierwsze czytanie rządowego projektu ustawy o zmianie ustaw w celu wsparcia odbiorców energii elektrycznej, paliw gazowych i ciepła oraz niektórych innych ustaw",
                    "speakers": [],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 29. porządku dziennego: Pierwsze czytanie poselskiego projektu ustawy o zmianie ustaw w celu wsparcia odbiorców energii elektrycznej, paliw gazowych i ciepła oraz niektórych innych ustaw",
                    "speakers": [
                        {
                            "position": "Minister Klimatu i Środowiska",
                            "name": "Anna Łukaszewska-Trzeciakowska",
                        },
                        {"position": "Poseł", "name": "Krzysztof Gadowski"},
                        {"position": "Poseł", "name": "Waldemar Buda"},
                        {"position": "Poseł", "name": "Janusz Kowalski"},
                        {"position": "Poseł", "name": "Tomasz Piotr Nowak"},
                        {"position": "Poseł", "name": "Krzysztof Gadowski"},
                        {"position": "Poseł", "name": "Ireneusz Zyska"},
                        {"position": "Poseł", "name": "Paulina Hennig-Kloska"},
                        {"position": "Poseł", "name": "Andrzej Grzyb"},
                        {"position": "Poseł", "name": "Dariusz Wieczorek"},
                        {"position": "Poseł", "name": "Krzysztof Mulawa"},
                        {"position": "Poseł", "name": "Zbigniew Krzysztof Kuźmiuk"},
                        {"position": "Poseł", "name": "Jarosław Wałęsa"},
                        {"position": "Poseł", "name": "Bartosz Romowicz"},
                        {"position": "Poseł", "name": "Ireneusz Raś"},
                        {"position": "Poseł", "name": "Roman Fritz"},
                        {"position": "Poseł", "name": "Andrzej Gawron"},
                        {"position": "Poseł", "name": "Aleksander Miszalski"},
                        {"position": "Poseł", "name": "Ewa Szymanowska"},
                        {"position": "Poseł", "name": "Jacek Tomczak"},
                        {"position": "Poseł", "name": "Tadeusz Tomaszewski"},
                        {"position": "Poseł", "name": "Mariusz Krystian"},
                        {"position": "Poseł", "name": "Ewa Kołodziej"},
                        {"position": "Poseł", "name": "Sławomir Ćwik"},
                        {"position": "Poseł", "name": "Zbigniew Sosnowski"},
                        {"position": "Poseł", "name": "Paweł Rychlik"},
                        {"position": "Poseł", "name": "Karolina Pawliczak"},
                        {"position": "Poseł", "name": "Michał Gramatyka"},
                        {"position": "Poseł", "name": "Andrzej Grzyb"},
                        {"position": "Poseł", "name": "Paweł Hreniak"},
                        {"position": "Poseł", "name": "Michał Szczerba"},
                        {"position": "Poseł", "name": "Marcin Skonieczka"},
                        {"position": "Poseł", "name": "Sebastian Kaleta"},
                        {"position": "Poseł", "name": "Małgorzata Gromadzka"},
                        {"position": "Poseł", "name": "Żaneta Cwalina-Śliwowska"},
                        {"position": "Poseł", "name": "Zbigniew Dolata"},
                        {"position": "Poseł", "name": "Iwona Karolewska"},
                        {"position": "Poseł", "name": "Izabela Bodnar"},
                        {"position": "Poseł", "name": "Piotr Müller"},
                        {"position": "Poseł", "name": "Agnieszka Pomaska"},
                        {"position": "Poseł", "name": "Ewa Schädler"},
                        {"position": "Poseł", "name": "Małgorzata Golińska"},
                        {"position": "Poseł", "name": "Zbigniew Bogucki"},
                        {"position": "Poseł", "name": "Cezary Tomczyk"},
                        {"position": "Poseł", "name": "Piotr Paweł Strach"},
                        {"position": "Poseł", "name": "Robert Gontarz"},
                        {"position": "Poseł", "name": "Michał Kołodziejczak"},
                        {"position": "Poseł", "name": "Rafał Komarewicz"},
                        {"position": "Poseł", "name": "Marcin Porzucek"},
                        {"position": "Poseł", "name": "Jagna Marczułajtis-Walczak"},
                        {"position": "Poseł", "name": "Wioleta Tomczak"},
                        {"position": "Poseł", "name": "Jan Warzecha"},
                        {"position": "Poseł", "name": "Urszula Sara Zielińska"},
                        {"position": "Poseł", "name": "Ireneusz Zyska"},
                        {"position": "Poseł", "name": "Tomasz Piotr Nowak"},
                        {"position": "Poseł", "name": "Radosław Fogiel"},
                        {"position": "Poseł", "name": "Krzysztof Gadowski"},
                        {"position": "Poseł", "name": "Joanna Borowiak"},
                        {"position": "Poseł", "name": "Krystyna Skowrońska"},
                        {"position": "Poseł", "name": "Paweł Szrot"},
                        {"position": "Poseł", "name": "Artur Jarosław Łącki"},
                        {"position": "Poseł", "name": "Jacek Ozdoba"},
                        {"position": "Poseł", "name": "Małgorzata Pępek"},
                        {"position": "Poseł", "name": "Małgorzata Golińska"},
                        {"position": "Poseł", "name": "Lucjan Marek Pietrzczyk"},
                        {"position": "Poseł", "name": "Barbara Bartuś"},
                        {"position": "Poseł", "name": "Henryk Szopiński"},
                        {"position": "Poseł", "name": "Mateusz Bochenek"},
                        {"position": "Poseł", "name": "Piotr Głowski"},
                        {"position": "Poseł", "name": "Marcin Gwóźdź"},
                        {"position": "Poseł", "name": "Jakub Rutnicki"},
                        {"position": "Poseł", "name": "Łukasz Schreiber"},
                        {"position": "Poseł", "name": "Witold Zembaczyński"},
                        {"position": "Poseł", "name": "Anna Kwiecień"},
                        {"position": "Poseł", "name": "Mirosława Nykiel"},
                        {"position": "Poseł", "name": "Józefa Szczurek-Żelazko"},
                        {"position": "Poseł", "name": "Grzegorz Rusiecki"},
                        {"position": "Poseł", "name": "Paweł Sałek"},
                        {"position": "Poseł", "name": "Patryk Jaskulski"},
                        {"position": "Poseł", "name": "Marek Sowa"},
                        {"position": "Poseł", "name": "Stanisław Lamczyk"},
                        {"position": "Poseł", "name": "Dariusz Joński"},
                        {"position": "Poseł", "name": "Adrian Witczak"},
                        {"position": "Poseł", "name": "Mirosław Suchoń"},
                        {"position": "Poseł", "name": "Marek Suski"},
                        {"position": "Poseł", "name": "Ireneusz Zyska"},
                        {
                            "position": "Minister Klimatu i Środowiska",
                            "name": "Anna Łukaszewska-Trzeciakowska",
                        },
                        {"position": "Poseł", "name": "Krzysztof Gadowski"},
                    ],
                },
                {"type": "BREAK"},
                {"type": "RESUME OBRADY"},
                {
                    "type": "HEADER",
                    "name": "Sprawy formalne",
                    "speakers": [{"position": "Poseł", "name": "Jacek Ozdoba"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 28. porządku dziennego: Pierwsze czytanie rządowego projektu ustawy o zmianie ustaw w celu wsparcia odbiorców energii elektrycznej, paliw gazowych i ciepła oraz niektórych innych ustaw (cd.)",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 29. porządku dziennego: Pierwsze czytanie poselskiego projektu ustawy o zmianie ustaw w celu wsparcia odbiorców energii elektrycznej, paliw gazowych i ciepła oraz niektórych innych ustaw (cd.)",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [{"position": "Marszałek", "name": "Marszałek"}],
                },
                {
                    "type": "HEADER",
                    "name": "Punkt 31. porządku dziennego: Pierwsze czytanie przedstawionego przez Prezydium Sejmu projektu uchwały w sprawie zmiany Regulaminu Sejmu Rzeczypospolitej Polskiej",
                    "speakers": [
                        {"position": "Poseł", "name": "Monika Wielichowska"},
                        {"position": "Poseł", "name": "Kazimierz Smoliński"},
                        {"position": "Poseł", "name": "Jarosław Urbaniak"},
                        {"position": "Poseł", "name": "Łukasz Osmalak"},
                        {"position": "Poseł", "name": "Michał Pyrzyk"},
                        {"position": "Poseł", "name": "Tadeusz Tomaszewski"},
                        {"position": "Poseł", "name": "Michał Wawer"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Jarosław Wałęsa"},
                        {"position": "Poseł", "name": "Grzegorz Rusiecki"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Kazimierz Smoliński"},
                        {"position": "Poseł", "name": "Łukasz Schreiber"},
                        {"position": "Poseł", "name": "Andrzej Gawron"},
                        {"position": "Poseł", "name": "Marcin Porzucek"},
                        {"position": "Poseł", "name": "Barbara Bartuś"},
                        {"position": "Poseł", "name": "Sylwester Tułajew"},
                        {"position": "Poseł", "name": "Jarosław Urbaniak"},
                        {"position": "Poseł", "name": "Krystyna Skowrońska"},
                        {"position": "Poseł", "name": "Michał Szczerba"},
                        {"position": "Poseł", "name": "Marek Jakubiak"},
                        {"position": "Poseł", "name": "Monika Wielichowska"},
                    ],
                },
                {"type": "BREAK"},
                {"type": "RESUME OBRADY"},
                {
                    "type": "HEADER",
                    "name": "Punkt 31. porządku dziennego (cd.)",
                    "speakers": [],
                },
                {
                    "type": "VOTING",
                    "speakers": [
                        {"position": "Marszałek", "name": "Marszałek"},
                        {"position": "Poseł", "name": "Łukasz Schreiber"},
                        {"position": "Poseł", "name": "Kazimierz Smoliński"},
                        {"position": "Poseł", "name": "Bogdan Andrzej Zdrojewski"},
                        {"position": "Poseł", "name": "Łukasz Osmalak"},
                        {"position": "Poseł", "name": "Michał Pyrzyk"},
                        {"position": "Poseł", "name": "Tadeusz Tomaszewski"},
                        {"position": "Poseł", "name": "Michał Wawer"},
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Marek Jakubiak"},
                    ],
                },
                {
                    "type": "HEADER",
                    "name": "Oświadczenia",
                    "speakers": [
                        {"position": "Poseł", "name": "Anna Dąbrowska-Banaszek"},
                        {"position": "Poseł", "name": "Łukasz Kmita"},
                        {"position": "Poseł", "name": "Jarosław Wałęsa"},
                        {"position": "Poseł", "name": "Tadeusz Tomaszewski"},
                        {"position": "Poseł", "name": "Patryk Gabriel"},
                        {"position": "Poseł", "name": "Aleksander Mikołaj Mrówczyński"},
                        {
                            "position": "Poseł",
                            "name": "Magdalena Małgorzata Kołodziejczak",
                        },
                        {"position": "Poseł", "name": "Grzegorz Braun"},
                        {"position": "Poseł", "name": "Bartosz Zawieja"},
                        {"position": "Poseł", "name": "Zbigniew Bogucki"},
                        {"position": "Poseł", "name": "Grzegorz Adam Płaczek"},
                        {"position": "Poseł", "name": "Waldemar Andzel"},
                        {"position": "Poseł", "name": "Klaudia Jachira"},
                        {"position": "Poseł", "name": "Szymon Giżyński"},
                        {"position": "Poseł", "name": "Paweł Bliźniuk"},
                        {"position": "Poseł", "name": "Barbara Bartuś"},
                        {"position": "Poseł", "name": "Henryk Szopiński"},
                        {"position": "Poseł", "name": "Bartosz Romowicz"},
                        {"position": "Poseł", "name": "Norbert Jakub Kaczmarczyk"},
                        {"position": "Poseł", "name": "Ewa Leniart"},
                        {"position": "Poseł", "name": "Piotr Uruski"},
                        {"position": "Poseł", "name": "Dariusz Matecki"},
                        {"position": "Poseł", "name": "Wioleta Tomczak"},
                        {"position": "Poseł", "name": "Michał Kołodziejczak"},
                        {"position": "Poseł", "name": "Anna Kwiecień"},
                    ],
                },
                {"type": "BREAK"},
                {
                    "type": "HEADER",
                    "name": "Załącznik – Teksty wystąpień niewygłoszonych",
                    "speakers": [{"position": "Poseł", "name": "Grzegorz Lorek"}],
                },
            ],
        )


if __name__ == "__main__":
    unittest.main()
